// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import PlacesController from "./places_controller.js"
application.register("places", PlacesController)

import TogglePasswordController from "./toggle_password_controller.js";
application.register("toggle-password", TogglePasswordController)

import TagsController from "./tags_controller.js"
application.register("tags", TagsController)

import PhotosController from "./photos_controller.js"
application.register("photos", PhotosController)

import MealsController from "./meals_controller.js"
application.register("meals", MealsController)

import DollarPriceRangeController from "./dollar_price_range_controller.js"
application.register("dollar-price-range", DollarPriceRangeController)

import CategoryController from "./category_controller.js"
application.register("category", CategoryController)