// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import PlacesController from "./places_controller.js"
application.register("places", PlacesController)

import TogglePasswordController from "./toggle_password_controller.js";
application.register("toggle-password", TogglePasswordController)

import TagsController from "./tags_controller.js"
application.register("tags", TagsController)